"""
This file is automatically generated by the autogen package.
Please edit the marked area only. Other areas will be
overwritten when autogen is rerun.
"""

from setuptools import setup

params = dict(
    name='slab',
    description='slab',
    version='2.0.0',
    url='https://dagshub.com/Omdena/SustainLab.git',
    install_requires=['Requests', 'pandas', 'numpy', 'dask', 'scikit_learn',
                      'spacy', 'PyPDF2', 'tqdm', 'transformers', 'prefect', 'pikepdf'],
    packages=['slab'],
    package_data={},
    include_package_data=True,
    py_modules=[],
    scripts=None)

########## EDIT BELOW THIS LINE ONLY ##########


########## EDIT ABOVE THIS LINE ONLY ##########

setup(**params)
