"""
This file is automatically generated by the autogen package.
Please edit the marked area only. Other areas will be
overwritten when autogen is rerun.
"""

from setuptools import setup

params = dict(
    name='slab',
    description='slab',
    version='0.0.0',
    url='https://dagshub.com/Omdena/SustainLab.git',
    install_requires=['spacy', 'scikit_learn', 'Requests', 'layoutparser', 'numpy', 'dask',
                      'pikepdf', 'prefect', 'pandas', 'tqdm', 'PyPDF2', 'pdf2image', 'transformers'],
    packages=['slab', 'slab.model', 'slab.preprocess'],
    package_data={'slab': ['logging.yml'], 'slab/preprocess': ['README']},
    include_package_data=True,
    py_modules=[],
    scripts=['scripts/preprocess.py'])

########## EDIT BELOW THIS LINE ONLY ##########


########## EDIT ABOVE THIS LINE ONLY ##########

setup(**params)
